version: "3.9"
services:
  # redis:
  #   container_name: urls_cache
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"
  #   command: redis-server --save 20 1 --loglevel warning --requirepass secretpass1
    
  postgres:
    container_name: urlsdb
    image: postgres:latest
    environment:
      POSTGRES_DB: "urls"
      POSTGRES_USER: "someuser"
      POSTGRES_PASSWORD: "secretpass"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U someuser -d urls"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  
  url-shortener:
    container_name: url-shortener
    build: ./
    ports:
      - '80:80'
    depends_on:
      postgres:
        condition: service_healthy