version: "3.9"
services:
  postgres:
    container_name: urlsdb
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  
  url-shortener:
    container_name: url-shortener
    build: ./
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      postgres:
        condition: service_healthy