version: "3.9"
services:

  postgres:
    container_name: urls-postgres
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./migrations/000001_user_table.up.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  mongo:
    container_name: urls-mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

    ports:
      - "27017:27017"
  
  url-shortener:
    container_name: url-shortener
    build: ./
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      postgres:
        condition: service_healthy