name: Main workflow file

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres

        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: run mock tests
        run: go test -v ./...
        env:
          HOST: http://localhost
          PORT: :8080
          DB_URL: postgres://postgres:postgres@localhost:5432/postgres
          DB_NAME: postgresql